## PyTorch Start and Use

In [2]:
# Libraries
import numpy as np 
import pandas as pd 

import torch

In [33]:
def activation(x):
    
    # Sigmoid Activation 
    return 1/(1 + torch.exp(-x))

In [9]:
## Generate some data 
torch.manual_seed(7) # Set the random seed 

# Features are 5 random normal variables 
features = torch.randn((1, 5))

# Generate weights for the features 
weights = torch.randn_like(features)

# and a bias term 
bias = torch.randn((1, 1))

In [34]:
# Calculate the ouptput of this network
output = activation(torch.mm(features, weights.T) + bias)

In [37]:
weights.reshape(5, 1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [39]:
w = weights.reshape(5, 1)

## Multilayer Model

In [59]:
## Generate some random data
torch.manual_seed(7)

# Generate features
features = torch.randn((1, 3))

# Define the size of each layer in our netowrk 
n_input = features.shape[1]
n_hidden = 2  # Number of hidden units 
n_output = 1  # number of output units

# Weights for inputs to hidden layer 
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to outputs 
W2 = torch.randn(n_hidden, n_output)

# Bias Terms 
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [60]:
h= activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
output

tensor([[0.3171]])

## Numpy to Torch and back

In [61]:
a = np.random.randn(4, 3)
a

array([[-0.53179332,  1.86322441,  1.94352348],
       [-2.63318819,  0.291824  ,  1.54809603],
       [ 0.2377769 ,  1.67265354,  0.58028972],
       [-0.88236909, -0.95554113,  0.57384867]])

In [62]:
b = torch.from_numpy(a)
b

tensor([[-0.5318,  1.8632,  1.9435],
        [-2.6332,  0.2918,  1.5481],
        [ 0.2378,  1.6727,  0.5803],
        [-0.8824, -0.9555,  0.5738]], dtype=torch.float64)

In [63]:
b.numpy()

array([[-0.53179332,  1.86322441,  1.94352348],
       [-2.63318819,  0.291824  ,  1.54809603],
       [ 0.2377769 ,  1.67265354,  0.58028972],
       [-0.88236909, -0.95554113,  0.57384867]])

In [64]:
# Shared memory model
b.mul_(2)

tensor([[-1.0636,  3.7264,  3.8870],
        [-5.2664,  0.5836,  3.0962],
        [ 0.4756,  3.3453,  1.1606],
        [-1.7647, -1.9111,  1.1477]], dtype=torch.float64)

In [65]:
a

array([[-1.06358664,  3.72644882,  3.88704697],
       [-5.26637638,  0.58364801,  3.09619206],
       [ 0.47555379,  3.34530709,  1.16057944],
       [-1.76473818, -1.91108225,  1.14769734]])